package shared

DEFAULT_WINDOW_TITLE :: "Chip-8"
DEFAULT_DISPLAY_SCALE :: 10
DEFAULT_TARGET_FPS :: 60

DISPLAY_WIDTH :: 64
DISPLAY_HEIGHT :: 32
DISPLAY_SIZE :: DISPLAY_WIDTH * DISPLAY_HEIGHT

MEMORY_SIZE :: 4096
MEMORY_FONT_START_ADDRESS :: 0x50
MEMORY_ROM_START_ADDRESS :: 0x200

STACK_SIZE :: 16

REGISTERS_SIZE :: 16

KEYPAD_SIZE :: 16

CYCLES_PER_FRAME :: 11
